name: Build and Release

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Executable
      run: |
        dotnet publish -c Release -r win-x64 --self-contained true -o ./publish
        # Zipping the publish directory
        Compress-Archive -Path ./publish/* -DestinationPath ./AnimeVoices.zip
      shell: pwsh

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AnimeVoices
        path: ./publish

  release:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: AnimeVoices

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: "AnimeVoices"
        body: |
          **AnimeVoices** is now released!
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./AnimeVoices.zip
        asset_name: AnimeVoices.zip
        asset_content_type: application/zip
